---

R1:
  hostname: 192.168.4.201
  platform: "juniper_junos"
  username: "john"
  password: "Juniper1"
  groups:
    - juniper_group
  data:
    device_name: "R1"


R2:
  hostname: 192.168.4.202
  platform: "cisco_ios"
  username: "john"
  password: "cisco"
  groups:
    - cisco_group
  data:
    device_name: "R2"
